### ISSUE TITLE
FreeBSD is not supported

### ISSUE THREAD

**Issue by yegor256** [yegor256/total#4]
Let's implement `Total::FreeBSD` class and test it.

**Comment by EvilKhaosKat** [comment]
Pull request #5

**Comment by EvilKhaosKat** [comment]
Pull request #5

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.0`

**Comment by EvilKhaosKat** [comment]
> @EvilKhaosKat your fork is gone, I added files manually: [8c4d9a5](https://github.com/yegor256/total/commit/8c4d9a59cc2e4d32c77f838bb5b1b04a9ea1e5ee)

Sorry for that, @yegor256, I didn't think it would cause necessity of extra actions from your side =(
